CREATE TABLE `t08_home` (
	`id` int(11) NOT NULL,
	`c` int(11) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
insert into t08_home(id, c) values(1,1),(2,2),(3,3),(4,4);

START TRANSACTION WITH CONSISTENT SNAPSHOT;
SELECT c FROM t08_home WHERE id = 1;
COMMIT;

START TRANSACTION WITH CONSISTENT SNAPSHOT;
UPDATE t08_home SET c = 0
SELECT SLEEP(30)
COMMIT;